import { ProgramaSoftware } from '../modelos/programa_software.js';

// Checklist Migración XStore 2026 — software y aplicaciones
export const PROGRAMAS_SOFTWARE = [
  new ProgramaSoftware({
    numero: 1,
    id: 'javapos',
    nombre: 'Configuración de JavaPOS',
    descripcion: 'Impresora y gaveta de dinero',
    detalle: 'Ingresar a la ruta para configurar la impresora y la gaveta de dinero:\n[[C:\\Program Files\\EPSON\\JavaPOS\\SetupPOS]]\n\nEjecutar SetupPOS como administrador y elegir la categoría y el modelo de impresora que use la tienda.',
    imagenes: ['/software/s01-b.png', '/software/s01-a.png', '/software/s01-d.png', '/software/s01-c.png', '/software/s01-f.png', '/software/s01-e.png', '/software/s01-g.png', '/software/s01-h.png', '/software/s01-j.png', '/software/s01-i.png'],
    notas: {
      '/software/s01-b.png': 'Si al hacer clic derecho NO aparece "Ejecutar como administrador", mantené presionado Ctrl + Shift y hacé clic en el programa para abrirlo como administrador.',
    },
  }),
  new ProgramaSoftware({
    numero: 2,
    id: 'cortex',
    nombre: 'Instalación de Cortex XDR',
    descripcion: 'Antivirus',
    detalle: 'Ingresar a la ruta para instalar el antivirus:\n[[D:\\Instaladores\\Cortex\\TAMBO]]',
    imagenes: ['/software/s02-b.png', '/software/s02-a.png'],
    notas: { '/software/s02-b.png': 'Antivirus Cortex XDR — presioná Shift + clic derecho y ejecutá con el usuario Administrator.' },
  }),
  new ProgramaSoftware({
    numero: 3,
    id: 'zabbix',
    nombre: 'Instalación de Zabbix',
    descripcion: 'Monitoreo',
    detalle: 'El instalador está en la raíz del disco [[D:\\]].\n\nEjecutar con el usuario Administrator y dar todo a "Siguiente" hasta finalizar.\n\nÚnico dato a tener en cuenta — IP: [[10.180.13.201]]',
    imagenes: ['/software/s03-c.png', '/software/s03-a.png', '/software/s03-e.png', '/software/s03-d.png', '/software/s03-b.png'],
    notas: {
      '/software/s03-c.png': 'Zabbix (monitoreo) — ejecutar con el usuario Administrator.',
      '/software/s03-d.png': 'Validar el HOSTNAME y digitar la MISMA IP en ambas casillas: 10.180.13.201',
    },
  }),
  new ProgramaSoftware({
    numero: 4,
    id: 'chrome',
    nombre: 'Configuración de Chrome',
    descripcion: 'Sesión y favoritos',
    detalle: 'a. Al abrir Chrome por primera vez: !!INICIAR SESIÓN CON EL CORREO DE TIENDA!! para activar la sincronización.\n\nb. Agregar como favorito Mi Tienda e !!INICIAR SESIÓN CON GOOGLE!!:\n[[https://mitienda.lindcorp.pe/]]\n\nc. Agregar GLPI e !!INICIAR SESIÓN CON LA CUENTA DE RED!! de la tienda (guardar la contraseña):\n[[https://helpdesk.lindcorptiendas.net/]]',
    imagenes: ['/software/s04-a.png', '/software/s04-b.png', '/software/s04-c.png', '/software/s04-d.png', '/software/s04-e.png', '/software/s04-f.png', '/software/s04-g.png'],
    notas: { '/software/s04-a.png': 'Chrome — primero iniciar sesión con el correo de tienda.' },
  }),
  new ProgramaSoftware({
    numero: 5,
    id: 'barra-tareas',
    nombre: 'Configuración de barra de tareas',
    descripcion: 'Anclar aplicaciones',
    detalle: 'Dejar ancladas en la barra de tareas las siguientes aplicaciones:\n· Chrome\n· Administrador de tareas\n· Ejecutar',
    imagenes: ['/software/s05-a.png', '/software/s05-b.png'],
    notas: { '/software/s05-a.png': 'Anclar: Chrome, Administrador de tareas y Ejecutar.' },
  }),
  new ProgramaSoftware({
    numero: 6,
    id: 'lector-barras',
    nombre: 'Configuración del lector de barras',
    descripcion: 'Códigos según la marca',
    detalle: 'Escanear los códigos según la marca del lector:\n· DATALOGIC\n· ZEBRA\n· HONEYWELL\n· CBX',
    imagenes: ['/software/s06-a.png', '/software/s06-b.png', '/software/s06-c.png', '/software/s06-d.png'],
    notas: { '/software/s06-a.png': 'Lector de barras — escanear el código de TU marca.' },
  }),
  new ProgramaSoftware({
    numero: 7,
    id: 'utility-epson',
    nombre: 'Configuración de Utility Epson',
    descripcion: 'Según modelo de impresora',
    detalle: 'Los instaladores están en:\n[[D:\\Instaladores\\Utility]]\n\nElegir según el modelo de impresora que use la tienda.',
    imagenes: ['/software/s07-a.png', '/software/s07-b.png', '/software/s07-c.png', '/software/s07-d.png', '/software/s07-e.png'],
    notas: { '/software/s07-a.png': 'Utility Epson — elegir según el modelo de impresora.' },
  }),
  new ProgramaSoftware({
    numero: 8,
    id: 'geovictoria',
    nombre: 'Instalación de GeoVictoria',
    descripcion: 'Biométrico',
    detalle: 'Primero instalar el controlador del biométrico (huellero). Ruta de instaladores:\n[[D:\\Instaladores\\HUELLERO]]\n\nLuego instalar GeoVictoria.',
    imagenes: ['/software/s08-a.png', '/software/s08-b.png', '/software/s08-c.png', '/software/s08-d.png', '/software/s08-e.png', '/software/s08-f.png', '/software/s08-g.png'],
    notas: { '/software/s08-a.png': 'GeoVictoria — primero instalar el controlador del huellero.' },
  }),
  new ProgramaSoftware({
    numero: 9,
    id: 'rumi',
    nombre: 'Instalación de RUMI',
    descripcion: 'Desde el servidor',
    detalle: 'El instalador actualizado está en el servidor [[10.180.11.144]].\n\nRuta completa:\n[[\\\\10.180.11.144\\instaladores$\\XSTORE_2026\\Instaladores]]',
    imagenes: ['/software/s09-a.png', '/software/s09-b.png', '/software/s09-c.png', '/software/s09-d.png', '/software/s09-e.png', '/software/s09-f.png'],
    notas: { '/software/s09-a.png': 'RUMI — instalador en el servidor 10.180.11.144' },
  }),
  new ProgramaSoftware({
    numero: 10,
    id: 'izipay',
    nombre: 'Validación de Izipay',
    descripcion: 'Simulador del POS',
    detalle: 'Verificar que esté conectado correctamente a la AIO. Una vez que el POS termina de encender por completo, ejecutar el simulador ubicado en:\n[[C:\\Program Files (x86)\\Caja Windows APIREST - PinPad - 6.4\\APIREST\\Simulador]]',
    imagenes: ['/software/s10-a.png', '/software/s10-b.png'],
    notas: { '/software/s10-a.png': 'Izipay — el POS debe estar 100% encendido antes.' },
  }),
];
